name: Daily Commit


on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  
permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make daily changes
        run: echo "$(date)" >> daily_commit.txt

      - name: Set up Git
        run: |
          git config --global user.email "jpdelgado9641@gmail.com"
          git config --global user.name "juanPDN"
          
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "Daily commit $(date)"
          git push
